name: pizza_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  envied: ^0.5.3
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
